### ISSUE TITLE
FileExistsError: [WinError 183] Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by gerroon** [JacquesLucke/blender_vscode#12]
Hi

I am not sure why I am having this error, after needing to change the name of the addon folder. I removed the folder from Vscode and then added the new folder

I used to work. I am using it on Windows 10 x64, Py 3.7.0

```
Executing task in folder ADDON: C:\BLENDER_28\blender.exe --python C:\DRIVE\DRIVE_APP_SETTINGS\VSCODE\.vscode-oss\extensions\jacqueslucke.blender-development-0.0.10\pythonFiles\launch.py <

Read prefs: C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\BLENDER_28\2.80\python
Traceback (most recent call last):
  File "C:\BLENDER_28\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'ADDON'
Traceback (most recent call last):
  File "C:\DRIVE\DRIVE_APP_SETTINGS\VSCODE\.vscode-oss\extensions\jacqueslucke.blender-development-0.0.10\pythonFiles\launch.py", line 16, in <module>
    allow_modify_external_python=os.environ['ALLOW_MODIFY_EXTERNAL_PYTHON'] == "yes",
  File "C:\DRIVE\DRIVE_APP_SETTINGS\VSCODE\.vscode-oss\extensions\jacqueslucke.blender-development-0.0.10\pythonFiles\include\blender_vscode\__init__.py", line 14, in startup
    path_mappings = load_addons.setup_addon_links(addon_paths)
  File "C:\DRIVE\DRIVE_APP_SETTINGS\VSCODE\.vscode-oss\extensions\jacqueslucke.blender-development-0.0.10\pythonFiles\include\blender_vscode\load_addons.py",
line 20, in setup_addon_links
    create_link_in_user_addon_directory(source_path, load_path)
  File "C:\DRIVE\DRIVE_APP_SETTINGS\VSCODE\.vscode-oss\extensions\jacqueslucke.blender-development-0.0.10\pythonFiles\include\blender_vscode\load_addons.py",
line 43, in create_link_in_user_addon_directory
    _winapi.CreateJunction(str(directory), str(link_path))
FileExistsError: [WinError 183] Cannot create a file when that file already exists
Saved session recovery to 'C:\Users\USER\AppData\Local\Temp\quit.blend'

Terminal will be reused by tasks, press any key to close it.
```

**Comment by gerroon** [comment]
Never mind I did not realize that, Vs addon was creating a symlink in the addon folder.

**Comment by Wilsman** [comment]
how did you fix this?

**Comment by gerroon** [comment]
Make sure you remove the existing addon  (in the addons folder) I think. Not sure how I did it exactly.

**Comment by Teriander** [comment]
I'm having the same problem.  Any chance you can elaborate on the exact file and folder you're referencing?  "existing addon in the addons folder" is a needle in a haystack.

**Comment by hotohoto** [comment]
For me the link was under `C:\Users\my_user_name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons`
