### ISSUE TITLE
ValueError: register_class(...): already registered as a subclass

### ISSUE THREAD

**Issue by gerroon** [JacquesLucke/blender_vscode#13]
Hi

I cant make sense of the error below if it is my addon is borking or the Vscode addon is borking. I am just trying to start Blender to see if the addon is loaded properly.

I am on Windows 10 x64 using Py 3.7.0 (system installation)

It is the default template from the addon

```
class MYADDONOperator(bpy.types.Operator):
    bl_idname = "object.MYADDON"
    bl_label = "MYADDON"

    def execute(self, context):
        return {'FINISHED'}

        #self.report({'INFO'}, "Works")




def register():
    bpy.utils.register_class(MYADDONOperator)

def unregister():
    bpy.utils.register_class(MYADDONOperator)

```

```
> Executing task in folder MYADDON: C:\BLENDER_28\blender.exe --python T:\APPS\VSCODE\.vscode-oss\extensions\jacqueslucke.blender-development-0.0.10\pythonFiles\launch.py <

Read prefs: C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\BLENDER_28\2.80\python
 * Serving Flask app "Blender Server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:7555/ (Press CTRL+C to quit)
Sending: {'type': 'setup', 'blenderPort': 7555, 'ptvsdPort': 6771, 'blenderPath': 'C:\\BLENDER_28\\blender.exe', 'scriptsFolder': 'C:\\BLENDER_28\\2.80\\scripts', 'addonPathMappings': [{'src': 'c:\\DEV\\DEV_Blender28_Python\\MYADDON', 'load': 'C:\\Users\\USER\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons\\MYADDON'}]}
Waiting for debug client.
Debug client attached.
Exception in module unregister(): 'C:\\Users\\USER\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons\\MYADDON\\__init__.py'
Traceback (most recent call last):
  File "C:\BLENDER_28\2.80\scripts\modules\addon_utils.py", line 313, in enable
    mod.unregister()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MYADDON\__init__.py", line 68, in unregister
    bpy.utils.register_class(MYADDONOperator)
ValueError: register_class(...): already registered as a subclass

Error: Traceback (most recent call last):
  File "C:\BLENDER_28\2.80\scripts\modules\addon_utils.py", line 313, in enable
    mod.unregister()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MYADDON\__init__.py", line 68, in unregister
    bpy.utils.register_class(MYADDONOperator)
ValueError: register_class(...): already registered as a subclass

Traceback (most recent call last):
  File "T:\APPS\VSCODE\.vscode-oss\extensions\jacqueslucke.blender-development-0.0.10\pythonFiles\include\blender_vscode\load_addons.py", line 32, in load
    bpy.ops.wm.addon_enable(module=addon_path.name)
  File "C:\BLENDER_28\2.80\scripts\modules\bpy\ops.py", line 200, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\BLENDER_28\2.80\scripts\modules\addon_utils.py", line 313, in enable
    mod.unregister()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MYADDON\__init__.py", line 68, in unregister
    bpy.utils.register_class(MYADDONOperator)
ValueError: register_class(...): already registered as a subclass


Sending: {'type': 'enableFailure', 'addonPath': 'c:\\DEV\\DEV_Blender28_Python\\MYADDON'}
```

**Comment by JacquesLucke** [comment]
You accidently call `register_class` in your `unregister` function in line 68 in the `__init__.py` file.

**Comment by gerroon** [comment]
Damn, sorry about that I will take a look at it tonight.
