### ISSUE TITLE
Alpha and Beta versions do not work

### ISSUE THREAD

**Issue by Zensurist** [JacquesLucke/blender_vscode#143]
Stable blender versions, currently blender 3.5, work very well with blender Development. But the alpha and beta versions, currently blender 3.6, unfortunately always crash, even when I run VSC as administrator. I get the following error:

```
Traceback (most recent call last):
  File "c:\Users\Andi\.vscode\extensions\jacqueslucke.blender-development-0.0.18\pythonFiles\launch.py", line 14, in <module>
    blender_vscode.startup(
  File "c:\Users\Andi\.vscode\extensions\jacqueslucke.blender-development-0.0.18\pythonFiles\include\blender_vscode\__init__.py", line 17, in startup
    communication.setup(editor_address, path_mappings)
  File "c:\Users\Andi\.vscode\extensions\jacqueslucke.blender-development-0.0.18\pythonFiles\include\blender_vscode\communication.py", line 21, in setup
    DEBUGPY_PORT = start_debug_server()
  File "c:\Users\Andi\.vscode\extensions\jacqueslucke.blender-development-0.0.18\pythonFiles\include\blender_vscode\communication.py", line 53, in start_debug_server
    debugpy.listen(("localhost", port))
  File "c:\Users\Andi\Downloads\blender-3.6.0-beta+v36.f87f119c2fc4-windows.amd64-release\blender-3.6.0-beta+v36.f87f119c2fc4-windows.amd64-release\3.6\python\lib\site-packages\debugpy\public_api.py", line 28, in wrapper
    from debugpy.server import api
  File "c:\Users\Andi\Downloads\blender-3.6.0-beta+v36.f87f119c2fc4-windows.amd64-release\blender-3.6.0-beta+v36.f87f119c2fc4-windows.amd64-release\3.6\python\lib\site-packages\debugpy\server\__init__.py", line 7, in <module>
    import debugpy._vendored.force_pydevd  # noqa
  File "c:\Users\Andi\Downloads\blender-3.6.0-beta+v36.f87f119c2fc4-windows.amd64-release\blender-3.6.0-beta+v36.f87f119c2fc4-windows.amd64-release\3.6\python\lib\site-packages\debugpy\_vendored\force_pydevd.py", line 44, in <module>
    preimport('pydevd', [
  File "c:\Users\Andi\Downloads\blender-3.6.0-beta+v36.f87f119c2fc4-windows.amd64-release\blender-3.6.0-beta+v36.f87f119c2fc4-windows.amd64-release\3.6\python\lib\site-packages\debugpy\_vendored\__init__.py", line 126, in preimport
    import_module(name)
  File "c:\Users\Andi\Downloads\blender-3.6.0-beta+v36.f87f119c2fc4-windows.amd64-release\blender-3.6.0-beta+v36.f87f119c2fc4-windows.amd64-release\3.6\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\Andi\Downloads\blender-3.6.0-beta+v36.f87f119c2fc4-windows.amd64-release\blender-3.6.0-beta+v36.f87f119c2fc4-windows.amd64-release\3.6\python\lib\site-packages\debugpy\_vendored\pydevd\pydevd.py", line 74, in <module>
    from _pydevd_bundle.pydevd_concurrency_analyser.pydevd_concurrency_logger import ThreadingLogger, AsyncioLogger, send_concurrency_message, cur_time
ModuleNotFoundError: No module named '_pydevd_bundle.pydevd_concurrency_analyser.pydevd_concurrency_logger'
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by CGArtPython** [comment]
Hey @Zensurist,

I just got today's 3.6 BETA Build and was able to launch and run my script 

https://builder.blender.org/download/daily/
`blender-3.6.0-beta+v36.d79524e3098e-windows.amd64-release.zip`

**Comment by Zensurist** [comment]
I just tried it again with the current blender 3.6 beta. Unfortunately, the same error occurred.
Apparently there were other people with the same problem, where they then had to rename a folder called "code" to get it working again. But I don't have a folder named code.

https://stackoverflow.com/questions/53500500/modulenotfounderror-no-module-named-pydevd-bundle

**Comment by Mateusz-Grzelinski** [comment]
@Zensurist is this still relevant? I could not reproduce then running `blender-3.6.14-windows-x64`

**Comment by Zensurist** [comment]
I can't say whether it is still relevant, because the workflow has changed anyway due to the new extensions.
I'll get back to you when I get my add-ons ready for blender 4.3.

**Comment by Mateusz-Grzelinski** [comment]
I will close as 3.6 is not alfa or beta for a long time and seems to work. In case of issues do not hesitate to ask/reopen.
