### ISSUE TITLE
It cant register ,  bpy_struct "Scene" registration error: 

### ISSUE THREAD

**Issue by gerroon** [JacquesLucke/blender_vscode#18]
It seems like the Vscode addon has issues with registering this. If I start Blender the usuak way my addon loads and everything works, that is not the case when I run Blender with Blender:start

```
class ADDONPropertyGrp(PropertyGroup):
    testint = bpy.props.IntProperty(  
        name="testint",
        description="",
        default=1,
        min=1,
        )



```

registered like this

```
def register():
        bpy.types.Scene.ADDONPropertyGrp = bpy.props.PointerProperty(
                                    type=ADDONPropertyGrp)

def unregister():
    
    del bpy.types.Scene.ADDONPropertyGrp

```

```
Traceback (most recent call last):
  File "C:\VSCODE\.vscode-oss\extensions\jacqueslucke.blender-development-0.0.10\pythonFiles\include\blender_vscode\load_addons.py", line 32, in load
    bpy.ops.wm.addon_enable(module=addon_path.name)
  File "C:\BLENDER_28\2.80\scripts\modules\bpy\ops.py", line 200, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\BLENDER_28\2.80\scripts\modules\addon_utils.py", line 393, in enable
    mod.register()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\ADDON\__init__.py", line 457, in register
    type=ADDONPropertyGrp)
ValueError: bpy_struct "Scene" registration error: ADDONPropertyGrp could not register

```

**Comment by gerroon** [comment]
nevermind :( the error was cryptic was not showing the real issue, typo somewhere
