### ISSUE TITLE
AttributeError: Calling operator "bpy.ops.preferences.addon_enable" error, could not be found

### ISSUE THREAD

**Issue by BlenderViza** [JacquesLucke/blender_vscode#32]
Windows 10 1803  64 bit  Blender 2.80 Beta 2019-01-11 23:51
```
Traceback (most recent call last):
  File "C:\Users\BlenderViza\.vscode\extensions\jacqueslucke.blender-development-0.0.11\pythonFiles\include\blender_vscode\**load_addons.py**", line 32, in load
    bpy.ops.preferences.addon_enable(module=addon_path.name)
  File "e:\Armory\Armory_06beta_win64\2.80\scripts\modules\bpy\ops.py", line 200, in __call__
    ret = op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.preferences.addon_enable" error, could not be found
Sending: {'type': 'enableFailure', 'addonPath': 'c:\\example\\_Blender\\AddOn\\2.8\\test'}
Armory: Proxy objects synchronized
```
I changed it back [see issue #27](https://github.com/JacquesLucke/blender_vscode/issues/27) to 

`bpy.ops.wm.addon_enable(module=addon_path.name)`

and then it works.

**Comment by JacquesLucke** [comment]
Please use a newer version of Blender.

**Comment by BlenderViza** [comment]
OK, thank you!

**Comment by neonb88** [comment]
> OK, thank you!
@BlenderViza Which version worked for you?  Also, still on Windows 10?

**Comment by Mateusz-Grzelinski** [comment]
Right now officially supported blender version is 2.8.34 minimum.
