### ISSUE TITLE
Failed to install with Visual Studio 2017

### ISSUE THREAD

**Issue by EssenOH** [JacquesLucke/blender_vscode#47]
Hi.

Seems like, this extension is great to develop a new node with native C/C++ code and then I am trying to use it.

I'd like to stay with Visual Studio 2017 community because it is free and no request about license instead of the latest 2019 version.

so, can you update the installer to support VS2017 ? or upload it to market place for VS2017 ?

I guess current version can support only VS2019 because I can't directly install it via Visual Studio Market place following the introduction video then I have downloaded the installer, but it doesn't work with error as following : 

8/23/2019 1:48:14 AM - Searching for applicable products...
8/23/2019 1:48:14 AM - Found installed product - Global Location
8/23/2019 1:48:14 AM - Found installed product - Visual Studio Community 2017
8/23/2019 1:48:14 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by robertguetzkow** [comment]
This extension is for [Visual Studio Code](https://code.visualstudio.com/) not [Visual Studio](https://visualstudio.microsoft.com/).
